apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 8.11.4
  nodeSets:
    - name: default
      count: 1
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
            storageClassName: sc-ssd
      podTemplate:
        spec:
          securityContext:
            privileged: true
            runAsUser: 0
            fsGroup: 0
          initContainers:
            - name: sysctl
              command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']