apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es-testing
spec:
  version: 8.11.4
  nodeSets:
    - name: es-nodeSets
      count: 1
      config:
        node.store.allow_mmap: false