apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 8.11.4
  nodeSets:
    - name: default
      count: 1
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
            storageClassName: sc-ssd
      config:
        node.store.allow_mmap: false
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              env:
                - name: ES_JAVA_OPTS
                  value: '-Xms2g -Xmx2g'
              resources:
                limits:
                  memory: 4Gi
                requests:
                  memory: 4Gi
          initContainers:
            - name: chown
              command: ['sh', '-c', 'chown elasticsearch:elasticsearch /usr/share/elasticsearch/data']