apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 8.11.4
  nodeSets:
    - name: defaulto
      count: 1
      config:
        node.store.allow_mmap: false