apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
  namespace: elastic-system-2
spec:
  version: 8.11.4
  nodeSets:
    - name: default
      count: 1
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 30Gi
            storageClassName: sc-ssq
      podTemplate:
        spec:
          nodeSelector:
            nodeRole: eck
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
                runAsUser: 0
              command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
            - name: chown
              securityContext:
                privileged: true
                runAsUser: 0
              command: ['sh', '-c', 'chown elasticsearch:elasticsearch /usr/share/elasticsearch/data']